services:
  minecraft-create:
    image: itzg/minecraft-server:java21
    container_name: minecraft-create-test
    restart: "no"

    ports:
      - "25566:25565"

    environment:
      EULA: "TRUE"
      TYPE: "NEOFORGE"
      VERSION: "1.21.1"

      MEMORY: "6G"
      MAX_PLAYERS: "10"
      DIFFICULTY: "hard"
      MODE: "survival"
      PVP: "true"
      ONLINE_MODE: "true"
      MOTD: "Servidor Create"

    volumes:
      - ./data:/data

    stdin_open: true
    tty: true